/**
 * generated by Scrooge 3.0.5-SNAPSHOT
 */
package october

import com.twitter.scrooge.ThriftEnum

/** The types of actions that can be performed in a triple (subject, verb, object) */
case object Action {
  case object Read extends Action {
    val value = 0
    val name = "Read"
  }
  case object VoteUp extends Action {
    val value = 1
    val name = "VoteUp"
  }
  case object VoteDown extends Action {
    val value = 2
    val name = "VoteDown"
  }
  case object VoteUpNegate extends Action {
    val value = 3
    val name = "VoteUpNegate"
  }
  case object VoteDownNegate extends Action {
    val value = 4
    val name = "VoteDownNegate"
  }
  case object Post extends Action {
    val value = 5
    val name = "Post"
  }
  case object Comment extends Action {
    val value = 6
    val name = "Comment"
  }
  case object Report extends Action {
    val value = 7
    val name = "Report"
  }
  case object Tag extends Action {
    val value = 8
    val name = "Tag"
  }
  case object Follow extends Action {
    val value = 9
    val name = "Follow"
  }

  /**
   * Find the enum by its integer value, as defined in the Thrift IDL.
   * @throws NoSuchElementException if the value is not found.
   */
  def apply(value: Int): Action = {
    value match {
      case 0 => Read
      case 1 => VoteUp
      case 2 => VoteDown
      case 3 => VoteUpNegate
      case 4 => VoteDownNegate
      case 5 => Post
      case 6 => Comment
      case 7 => Report
      case 8 => Tag
      case 9 => Follow
      case _ => throw new NoSuchElementException(value.toString)
    }
  }

  /**
   * Find the enum by its integer value, as defined in the Thrift IDL.
   * Returns None if the value is not found
   */
  def get(value: Int): Option[Action] = {
    value match {
      case 0 => scala.Some(Read)
      case 1 => scala.Some(VoteUp)
      case 2 => scala.Some(VoteDown)
      case 3 => scala.Some(VoteUpNegate)
      case 4 => scala.Some(VoteDownNegate)
      case 5 => scala.Some(Post)
      case 6 => scala.Some(Comment)
      case 7 => scala.Some(Report)
      case 8 => scala.Some(Tag)
      case 9 => scala.Some(Follow)
      case _ => scala.None
    }
  }

  def valueOf(name: String): Option[Action] = {
    name.toLowerCase match {
      case "read" => scala.Some(Action.Read)
      case "voteup" => scala.Some(Action.VoteUp)
      case "votedown" => scala.Some(Action.VoteDown)
      case "voteupnegate" => scala.Some(Action.VoteUpNegate)
      case "votedownnegate" => scala.Some(Action.VoteDownNegate)
      case "post" => scala.Some(Action.Post)
      case "comment" => scala.Some(Action.Comment)
      case "report" => scala.Some(Action.Report)
      case "tag" => scala.Some(Action.Tag)
      case "follow" => scala.Some(Action.Follow)
      case _ => scala.None
    }
  }
}


/** The types of actions that can be performed in a triple (subject, verb, object) */
sealed trait Action extends ThriftEnum with Serializable